### ISSUE TITLE
IndoorPositioning not showing up under Location 

### ISSUE THREAD

**Issue by mprogers** [Esri/arcgis-maps-sdk-dotnet-samples#1259]
In the code base, the Location folder has 5 folders - but only 4 of them are showing up in the running app. The one that I want (of course), IndoorPositioning, does not appear.

<img width="1410" alt="Screenshot 2023-06-27 at 10 03 27 AM" src="https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/301461/09f6e92d-8d6f-4cfb-91e0-f4b13da8d7e2">

<img width="261" alt="Screenshot 2023-06-27 at 10 04 13 AM" src="https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/301461/8fbf2031-4ba0-4b3b-ad69-4f0ba5662382">

**Comment by williambohrmann3** [comment]
Hey @mprogers this sample is [intended to be disabled](https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/blob/7a0e75b69e05451f7ceb8b2c72bf4801e4267de6/src/MAUI/Maui.Samples/ArcGIS.Samples.Maui.csproj#L63) on Windows and Mac. It is enabled on iOS and Android devices - these portable devices are much better suited for IPS.

**Comment by mprogers** [comment]
Oh, that explains it! Thanks, William. Hey, when I run into IPS questions -- which is a guarantee -- where's the best place to get help?

**Comment by williambohrmann3** [comment]
You're welcome! [Esri Community](https://community.esri.com/t5/net-maps-sdk-questions/bd-p/arcgis-runtime-sdk-dotnet-questions) is the best place to post your .NET IPS questions. There are other boards if you're working with multiple SDKs.
