### ISSUE TITLE
[Bug] Button icons missing from UWP viewer

### ISSUE THREAD

**Issue by mstefarov** [Esri/arcgis-maps-sdk-dotnet-samples#1534]
### Platforms

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### Apps

- [ ] .NET MAUI
- [ ] WinUI
- [ ] WPF

### Bug Description

Testing our UWP viewer on a fresh Windows 11 install, looks like the icons are missing:
<img width="137" alt="{A47BA088-307A-4083-82D7-9894CC1B5BEA}" src="https://github.com/user-attachments/assets/ca75672e-f9cc-4d42-a231-dba0bffa9da1">

Is the Calcite icon font not getting packaged/deployed with the app?

### Steps to Reproduce

Open one of the affected samples in UWP sample viewer, with no Calcite fonts installed system-wide.

### Impacted Samples

CreateAndEditGeometries, SnapGeometryEdits

**Comment by duffh** [comment]
Well spotted, strangely it was working locally for me. 

PR: https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/pull/1545
