### ISSUE TITLE
Add security samples

### ISSUE THREAD

**Issue by rexhansen** [Esri/arcgis-maps-sdk-dotnet-samples#21]

**Comment by anttikajanus** [comment]
@rexhansen @mbranscomb is this still relevant

**Comment by rexhansen** [comment]
@anttikajanus @mbranscomb  The OAuth-web view samples are already in the current samples, which is good.  We likely need to add samples that show use of: 
1) client certificates
2) network credentials (IWA, basic)
3) refresh tokens
