### ISSUE TITLE
None of the LocalServer samples work for 100.6

### ISSUE THREAD

**Issue by marhja** [Esri/arcgis-maps-sdk-dotnet-samples#704]
None of the LocalServer samples work in ArcGIS Runtime SDK for .NET (WPF) 100.6. The Local Server starts, but all the samples get an error when trying to start a service.

I also tried to reacreate one of the samples in Visual Studio 2019 locally on my machine with the same result.

I've enabled logging using the ArcGIS Runtime Local Server Utility, but no logs or error reports get generated.

I'm running the ArcGIS Runtime SDK for .NET (WPF) built with ArcGIS Runtime SDK for .NET version 100.6.0.2513 installed from Windows Store and I've downloaded and installed ArcGIS Runtime Local Server SDK 100.6.0 from the ArcGIS for Developers Downloads page.

I also have ArcMap 10.5.1 and ArcGIS Pro 2.4.2 installed on my computer.

**Comment by dotMorten** [comment]
>  all the samples get an error when trying to start a service.

What is the error? I'm terrible at guessing :-)

**Comment by marhja** [comment]
It's a bit different for the different samples, but mostly that the map service could not be started because a map package could not be opened.

**Comment by dotMorten** [comment]
Thanks but could you provide the specific error message, the full call stack etc for at least one of them?

**Comment by marhja** [comment]
Running Local server feature layer sample displays the following error message:
![image](https://user-images.githubusercontent.com/7138368/67315868-bca4bd80-f507-11e9-87f8-437e1470262e.png)

Running Dynamic workspace raster sample and choosing the downloaded raster:
![image](https://user-images.githubusercontent.com/7138368/67316099-2329db80-f508-11e9-8b84-05d09c51f566.png)

This is the third computer I tried it on with the same results. I don't have Visual Studio on this one, so I cannot provide any error details from a local sample until tomorrow when I'm back at the office.

**Comment by mbranscomb** [comment]
Have you installed `Microsoft Visual C++ Redistributable for Visual Studio 2017`?

**Comment by marhja** [comment]
No, I had missed that prerequisite. :-)
Unfortunately it didn't help to install it (x64 version).
Reinstalling Local Server SDK after that didn't help either.
Neither did reinstalling the ArcGIS Runtime SDK for .NET (WPF).

**Comment by marhja** [comment]
When running the Local Server feature layer sample locally in VS2019 I get a ArcGISWebException from LocalFeatureService.StartAsync() with Message:
_Failed to create service pointsofinterest MapServer. Service failed to initialize: Error unpacking map package hr=0x80004005 (No ErrorInfo)_

and Response.RequestMessage:
_{Method: POST, RequestUri: 'http://127.0.0.1:50000/8dB9Gv/arcgis/rest/admin/createService', Version: 1.1, Content: System.Net.Http.FormUrlEncodedContent, Headers:
{
  User-Agent: ArcGISRuntime-NET/100.6
  User-Agent: (Windows 10.0.18362; Win64; WOW64; .NET 4.8.0)
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 149
}}_

and StackTrace (replaced customer name in src path):
   _at Esri.ArcGISRuntime.Http.ArcGISHttpClientHandler.ArcGISClientHandlerInternal.<SendAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Esri.ArcGISRuntime.LocalServices.LocalService.<StartServiceInternal>d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestLocalServer.MainWindow.<TestOpenMapPackageAsync>d__15.MoveNext() in C:\Dev\CustomerName\Src\TestLocalServer\TestLocalServer\MainWindow.xaml.cs:line 201_

In my computer at the office I also already had Microsoft Visual C++ Redistributable for Visual Studio 2017 installed.

**Comment by marhja** [comment]
I tried the [Sample Viewer built with 100.5](https://www.arcgis.com/home/item.html?id=fe91758702f24b19a3d736e423918ee7) and there all Local Server samples worked.

**Comment by mbranscomb** [comment]
@marhja 

Can you open `Control Panel` > `Programs` > `Programs and Features` then search for `C++` and paste a screen capture?

**Comment by marhja** [comment]
![image](https://user-images.githubusercontent.com/7138368/67524611-56f43500-f6b1-11e9-9d33-c9322bd3c5ea.png)

**Comment by marhja** [comment]
@mbranscomb  After I got the _Dynamic workspace shapefile_ sample working with Local Server SDK 100.5, I uninstalled that version and reinstalled 100.6 again. Now that sample works in the Sample Viewer app 100.6! The _Local Server feature layer_ sample also works now, but no other Local Server samples work.

**Comment by mbranscomb** [comment]
@marhja It's been some time since you opened this. Unfortunately we were not able to reproduce the issue you were seeing. If you are still having trouble with the samples and this issue specifically, feel free to reopen, otherwise if you have any issues working with the API please get in touch via [community.esri.com - runtime-sdk-dotnet-questions](https://community.esri.com/t5/arcgis-runtime-sdk-for-net/bd-p/arcgis-runtime-sdk-dotnet-questions).
