### ISSUE TITLE
Error when launching aplication in IOS

### ISSUE THREAD

**Issue by jorgemrht** [Esri/arcgis-maps-sdk-dotnet-samples#754]
When I install the following packages my application cannot be opened in my iPad but I can open in my simulator

https://www.nuget.org/packages/Esri.ArcGISRuntime.Xamarin.Forms/

https://www.nuget.org/packages/Esri.ArcGISRuntime.Toolkit.Xamarin.Forms/

The error that throws me is the following:

Library not loaded: @rpath/ArcGIS-arm64.framework/ArcGIS-arm64

  Reason: no suitable image found.  Did find:

  Referenced from: /private/var/containers/Bundle/Application/D235CB9C-EFFB-4E40-B64A-98D1361CB1D5/xxxxx.iOS.app/xxxxx.iOS

                /private/var/containers/Bundle/Application/D235CB9C-EFFB-4E40-B64A-98D1361CB1D5/xxxxx.iOS.app/Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64: code signature invalid for '/private/var/containers/Bundle/Application/D235CB9C-EFFB-4E40-B64A-98D1361CB1D5/xxxx.iOS.app/Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64'

                /private/var/containers/Bundle/Application/D235CB9C-EFFB-4E40-B64A-98D1361CB1D5/xxxxx.iOS.app/Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64: stat() failed with errno=1

**Comment by nCastle1** [comment]
@jorgemht Have you tried cleaning and deleting the bin & obj folders, then rebuilding the app? If that doesn't work, would you be able to share a copy of your solution so I can try to repro locally?
