### ISSUE TITLE
Error when load shapefile which doesn't have features

### ISSUE THREAD

**Issue by yh371174229** [Esri/arcgis-maps-sdk-dotnet-samples#771]
```
                ShapefileFeatureTable tarShpFeaTable = new ShapefileFeatureTable(sTarXzqFilePath);
                await tarShpFeaTable.LoadAsync();
```
①when load shapefile which doesn't have features，the wpf app will tell me `"SQL error or missing database"`
②I think it's a bug.when I delete all features,then I add new feature to shapefile,also can't success.the shapefile will be destroy

**Comment by mbranscomb** [comment]
@yh371174229 

Hi,

Please post questions regarding functionality of ArcGIS Runtime SDK for .NET in our [GeoNet community space](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net).

Thanks
