### ISSUE TITLE
offline routing in angular ESRI

### ISSUE THREAD

**Issue by AminBangash** [Esri/arcgis-maps-sdk-dotnet-samples#784]
Is there any way to find offline route between two points in esri arcgis api for javascript 4.15?

**Comment by mbranscomb** [comment]
Hi,

ArcGIS Runtime SDK for .NET is not currently supported for use in web applications. I recommend posting your question in [ArcGIS API for JavaScript community](https://community.esri.com/community/developers/web-developers/arcgis-api-for-javascript).

Thanks
