### ISSUE TITLE
Is Indoor Navigation possible with a Custom Map?

### ISSUE THREAD

**Issue by Druffl3** [Esri/arcgis-maps-sdk-dotnet-samples#811]
Is Indoor Navigation possible with a Custom Indoor Map I create for a certain building?

**Comment by nCastle1** [comment]
Yes, indoor navigation is possible with custom maps, both in online and offline scenarios.

**Comment by DivyaVaniChinta** [comment]
Can I have any sample code Indoor Navigation implemented in Xamarin.Forms ?

**Comment by mbranscomb** [comment]
@DivyaVaniChinta Here's a demo of indoor navigation implemented with what's available in the current release of the API: https://github.com/Esri/arcgis-runtime-demos-dotnet/tree/main/src/CampusRouting

Keep checking the release announcements for future enhancements in support for indoor navigation.
