### ISSUE TITLE
This service does not support the Map capability on android xamarin

### ISSUE THREAD

**Issue by tatsondev** [Esri/arcgis-maps-sdk-dotnet-samples#866]
```
ArcGISMapImageLayer baseLayer;
baseLayer = new ArcGISMapImageLayer(new Uri(EsriServerUrl));
await baseLayer.LoadAsync();
```
On Load of baseLayer, I am getting an exception (This service does not support the Map capability).
I am using Esri.ArcGISRuntime.Xamarin.Android v 100.7 package.
ArcGIS Service version v 10.81.

**Comment by mbranscomb** [comment]
Hi,

Are you having trouble with a specific sample in this repo or are you experiencing difficulty implementing this functionality in your own application? 

Thanks

**Comment by tatsondev** [comment]
@mbranscomb thanks for replying. I am having difficulty implementing my own application. If I use Esri.ArcGISRuntime.Xamarin.Android v 100.5 package seems to be working fine but when I updated it to v 100.7 then I am facing the above issue.  (This service does not support the Map capability).

![Screenshot 2021-03-03 at 9 18 40 AM](https://user-images.githubusercontent.com/15764298/109749970-9b76d580-7c01-11eb-8aa2-357c9e3180da.png)

**Comment by mbranscomb** [comment]
@tatsondev Thanks for posting your question in the Community - looks like it was solved in both threads.

https://community.esri.com/t5/arcgis-runtime-sdk-for-net/invalid-response-this-service-does-not-support-map-capability/m-p/1032970#M9857 / https://community.esri.com/t5/arcgis-runtime-sdk-for-net/invalid-response-this-service-does-not-support-map-capability/m-p/1032765#M9849
