### ISSUE TITLE
 public RuntimeImage InfoIcon => new RuntimeImage(new Uri("https://cdn3.iconfinder.com/data/icons/web-and-internet-icons/512/Information-256.png"));

### ISSUE THREAD

**Issue by tumens2009** [Esri/arcgis-maps-sdk-dotnet-samples#933]
var callout = new CalloutDefinition(popup.GeoElement);
                    callout.Tag = popup;
                    callout.ButtonImage = InfoIcon;
                    callout.OnButtonClick = new Action<object>((s) =>

it's not working on Android but working on IOs.

**Comment by mbranscomb** [comment]
Hi,

This repo is for issues directly related to the samples for ArcGIS Runtime SDK for .NET. For questions beyond the samples, please ask the [Esri Community](https://community.esri.com/t5/arcgis-runtime-sdk-for-net-questions/bd-p/arcgis-runtime-sdk-dotnet-questions).

Thanks
