### ISSUE TITLE
xamarin forms searchview error

### ISSUE THREAD

**Issue by tumens2009** [Esri/arcgis-maps-sdk-dotnet-samples#966]

**Comment by tumens2009** [comment]
<img width="991" alt="Screen Shot 2022-02-17 at 23 15 50" src="https://user-images.githubusercontent.com/73527930/154511773-2e6b9228-2580-47c5-a46f-45927527ea0a.png">

**Comment by mbranscomb** [comment]
Hi,

This repo is for issues directly related to the samples for ArcGIS Runtime SDK for .NET. For questions beyond the samples there are several support options available to you: https://developers.arcgis.com/net/support/.

Thanks
